/*
 * checkpattern.{cc,hh} -- element checks packets generated by SendPattern
 * Robert Morris
 *
 * Copyright (c) 1999-2000 Massachusetts Institute of Technology
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * Further elaboration of this license, including a DISCLAIMER OF ANY
 * WARRANTY, EXPRESS OR IMPLIED, is provided in the LICENSE file, which is
 * also accessible at http://www.pdos.lcs.mit.edu/click/license.html
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif
#include "checkpattern.hh"
#include "glue.hh"
#include "confparse.hh"

CheckPattern::CheckPattern()
{
  _len = 1;
  add_input();
  add_output();
}

CheckPattern::~CheckPattern()
{
}

int
CheckPattern::configure(const Vector<String> &conf, ErrorHandler *errh)
{
  return cp_va_parse(conf, this, errh,
		     cpUnsigned, "packet length", &_len,
		     0);
}

Packet *
CheckPattern::simple_action(Packet *p)
{
  unsigned i;

  if(p->length() != _len)
    click_chatter("CheckPattern: p->length() %d _len %d",
                p->length(), _len);

  for(i = 0; i < _len && i < p->length(); i++){
    if((p->data()[i]&0xff) != (i&0xff)){
      click_chatter("CheckPattern: i=%d pkt %02x wanted %02x",
                  i, p->data()[i] & 0xff, i & 0xff);
      break;
    }
  }

  return(p);
}

EXPORT_ELEMENT(CheckPattern)
