/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

#ifndef samplepackage_CLICK_CONFIG_H
#define samplepackage_CLICK_CONFIG_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "samplepackage"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "samplepackage 2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "samplepackage"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.0"

#endif /* samplepackage_CLICK_CONFIG_H */
