#!/usr/bin/perl -w

# make-linux-patch

# Make a patch file for a Linux kernel that adds our hooks.
# The resulting output can be used thus:
#  cd /usr/src/linux
#  patch -p0 -b < patch-file

# List of files that we modified and that should be patched.
# Each must be accompanied by a file.orig.
my @files = (
             "include/linux/netdevice.h",
             "include/linux/signal.h",
             "include/linux/skbuff.h",
             "include/net/neighbour.h",
             "net/core/skbuff.c",
             "net/core/dev.c",
             "net/sched/sch_generic.c",
             "net/netsyms.c",
	     "fs/proc/inode.c",
	     "drivers/net/tulip.c",
	     "drivers/net/acenic.c",
	     "drivers/net/acenic.h"
             );

$| = 1;
my $f;
foreach $f (@files) {
    print "\nIndex: $f\n";
    system("diff -u ${f}.orig $f");
}
