#ifndef CLICK_IP6CLASSIFIER_OPERATOR_HH
#define CLICK_IP6CLASSIFIER_OPERATOR_HH

CLICK_DECLS

namespace ip6classification {
enum Operator {
    EQUALITY,
    INEQUALITY,
    GREATER_THAN,
    GREATER_OR_EQUAL_THAN,
    LESS_THAN,
    LESS_OR_EQUAL_THAN,
};
};
CLICK_ENDDECLS

#endif  /* CLICK_IP6CLASSIFIER_OPERATOR_HH */
