#! /usr/local/bin/perl -w

use strict;

# NOTE: this script for linux 2.4.20 & similar

# Make a patch file for a Linux kernel that adds the grid WiFi hooks.
# The resulting output can be used thus:
#  cd /usr/src/linux
#  patch -p0 -b < patch-file

# List of files/directories that we modified and that should be patched.
# Each must be accompanied by a file.orig.
my @files = (
	     "include/linux/packet_anno.h",       # new file, must create empty .orig
	     "include/linux/click_wifi.h",        # new file, must create empty .orig
	     "drivers/net/wireless/click_wifi.c", # new file, must create empty .orig
	     "drivers/net/wireless/airo.c"
             );


$| = 1;

my $f;
foreach $f (@files) {
    print "\nIndex: $f\n";
    system("diff -u ${f}.orig $f");
}
