#!/usr/bin/perl 

# $Id: run-grid-node,v 1.3 2000/08/04 20:32:11 decouto Exp $

# usage: run-grid-node <ip-addr> [-no-gw -debug]

# assume we run in <clickdir>/conf XXX

$click = "../userlevel/click";
$click_debug = "cat";
$click_config_name = "../conf/grid3.click";

$GRID_GW = "18.26.8.1";
$GRID_NETMASK = "255.255.255.0";
$GRID_NET_HEX = "16/121a07"; # 18.26.7.*
$NBR_TIMEOUT = "2000"; # msecs
$HELLO_PERIOD = "500"; # msecs
$HELLO_JITTER = "100"; # msecs
$LR_PERIOD = "1300"; # msecs
$LR_JITTER = "300"; # msecs
$GRID_ETH_PROTO = "12/7FFF";
$GRID_NBR_ENCAP_PROTO = "15/03";

sub ip_to_hex {
    ($a, $b, $c, $d) = @_[0] =~ /(\d+)\.(\d+)\.(\d+)\.(\d+)/;
    return sprintf("%02x%02x%02x%02x", $a, $b, $c, $d);
}
	


if (@ARGV < 2) { 
    print stderr "usage: $0 <ip-addr> <interface> [no-gw]\n";
    exit 1;
}

$system_type = `uname`;
if (!($system_type =~ /Linux/ || 
      $system_type =~ /FreeBSD/)) {
    print stderr "This system is not supported\n";
    exit 1;
}


$grid_addr = $ARGV[0];
$grid_if = $ARGV[1];
$grid_gw = $GRID_GW;

$i = 0;
for ($i = 2; $i < @ARGV; $i++) {
    if ($ARGV[$i] eq "-debug") {
	$click = $click_debug;
	print "Using DEBUG command\n";
    }
    if ($ARGV[$i] eq "-no-gw") {
	$grid_gw = "0.0.0.0";
    }
}

print "Running Grid with address ", $grid_addr, " on interface ", $grid_if. "\n";
if ($grid_gw != "0.0.0.0") {
    print "Using Grid gateway ", $grid_gw, "\n";
}
else {
    print "NOT using Grid gateway\n";
}

# get MAC address

$ifconfig_out = `ifconfig $grid_if`;
$hw_addr = "";
$tun_dev_type = "";

if ($system_type =~ /Linux/) {
    if(!($ifconfig_out =~ /(([a-fA-F0-9]{2}:){5}[0-9a-fA-F]{2})/)){
	print "Unable to get MAC address";
	exit 1;
    }
    $hw_addr = $1;
    
    $tun_dev = "tap";
}
elsif ($system_type =~ /FreeBSD/) {
    if(!($ifconfig_out =~ /(([a-fA-F0-9]{2}:){5}[0-9a-fA-F]{2})/)){
	print "Unable to get MAC address\n";
	exit 1;
    }
    $hw_addr = $1;

    $tun_dev = "tun";
}
else {
    print stderr "This system is not supported\n";
    exit 1;
}

# turn off routing etc. for grid interface
# optionally setup default gw

if ($system_type =~ /Linux/) {
    system "ifconfig $grid_if down";
    system "ifconfig $grid_if 0";
}
elsif ($system_type =~ /FreeBSD/) {
    print stderr "Not yet implemented for this system\n";
    exit 1;
}
else {
    print stderr "This system is not supported\n";
    exit 1;
}


# fire up click, substituting appropriate values into the config file,
# and piping it into click stdin.

open(click_config_file, $click_config_name) || die "can't open click configuration ", $click_config_name, "\n";

$grid_addr_hex = ip_to_hex($grid_addr);

open(P, "| $click");
while(<click_config_file>) {
    
    s/GRID_NETMASK/$GRID_NETMASK/;
    s/GRID_NET_HEX/$GRID_NET_HEX/;
    s/NBR_TIMEOUT/$NBR_TIMEOUT/;
    s/HELLO_PERIOD/$HELLO_PERIOD/;
    s/HELLO_JITTER/$HELLO_JITTER/;
    s/LR_PERIOD/$LR_PERIOD/;
    s/LR_JITTER/$LR_JITTER/;
    s/GRID_ETH_PROTO/$GRID_ETH_PROTO/;
    s/GRID_NBR_ENCAP_PROTO/$GRID_NBR_ENCAP_PROTO/;
    s/GRID_GW/$grid_gw/;
    s/GRID_IP/$grid_addr/;
    s/GRID_HEX_IP/$grid_addr_hex/;
    s/NET_DEVICE/$grid_if/;
    s/MAC_ADDR/$hw_addr/;
    s/TUN_DEVICE_PREFIX/$tun_dev/;
    
    print P $_;
}
close P;
close click_config_file;
